name: admin_panel
description: Skill Qode Admin Management Panel
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  flutter_svg: ^2.0.6
  fluttertoast: ^8.2.1
  lottie: ^2.3.2
  google_fonts: ^4.0.4
  flutter_screenutil: ^5.8.1

  get: ^4.6.5
  get_storage: ^2.1.1

  dio: ^5.1.2
  connectivity_plus: ^4.0.1

  intl: ^0.18.1
  crypto: ^3.0.3
  url_launcher: ^6.1.11
  image_picker: ^0.8.7+5

  bitsdojo_window: ^0.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/json_file/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
